game:
  title: "Up Going"
  width: 500
  height: 700
  fps: 60

player:
  gravity: 48
  jump_power: -1080
  horizontal_speed: 360
  width: 30
  height: 30

platforms:
  base_height: 15
  min_width: 80
  max_width: 150
  speed: 120.0
  spacing: 120

generation:
  min_gap_y: 100
  max_gap_y: 250
  spawn_margin_top: 50
  spawn_rate: 100

scoring:
  multiplier: 0.1
