game:
  title: "Up Going"
  width: 405
  height: 720
  fps: 60

player:
  gravity: 1200         # Pixels/Second^2
  jump_power: -700      # Pixels/Second
  horizontal_speed: 400 # Pixels/Second
  width: 30
  height: 30
  jump_time_window: 0.15
  jump_buffer_duration: 0.1

platforms:
  base_height: 20
  min_width: 80
  max_width: 150
  speed: 80.0          # Pixels/Second downwards
  max_speed: 200.0
  spacing: 120
  auto_jump_chance: 0.2

generation:
  min_gap_y: 100
  max_gap_y: 250
  spawn_margin_top: 50
  spawn_rate: 100