game:
  title: "Up Going"
  width: 576
  height: 720
  fps: 60

player:
  gravity: 1200         # Pixels/Second^2
  jump_power: -700      # Pixels/Second
  horizontal_speed: 400 # Pixels/Second
  width: 30
  height: 30
  jump_time_window: 0.15

platforms:
  base_height: 20
  min_width: 80
  max_width: 150
  speed: 100.0          # Pixels/Second downwards
  spacing: 120

generation:
  min_gap_y: 100
  max_gap_y: 250
  spawn_margin_top: 50
  spawn_rate: 100

scoring:
  multiplier: 0.1